### ISSUE TITLE
Converter couldn't open file

### ISSUE THREAD

**Issue by amrojjeh** [LOLProjects/TerminalTouhou#1]
Problem: When I launch the executable in converter, I get the error message: `Failed to load image "                             ". Reason: Unable to open file`

I made a print in the first conditional, confirming that it's maxresdefault.jpg that could not load.

Compilation line: `cl /EHcs /I include main.cpp /link lib\*.lib`
Folder Hierarchy:
Converter
- include (The SFML include folder)
- lib (The SFML libraries)
- chars.png
- main.cpp
- main.exe
- maxresdefault.png
- test.png (as provided by the repo)
- All the SFML DLLs

Any ideas? I installed the 64 bit version of SFML. I also tried just using a c string for the file name, but that didn't work. Also I'm on Windows.

Wait why did I say that? You already know

**Comment by Guigui220D** [comment]
@dinglydo that was a build problem on your side no? Should this issue be closed?

**Comment by amrojjeh** [comment]
Yes
